name: Developer image
on:
  push:
    branches: [main]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: type=raw,value=dev
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
        
      - name: Build and push to DockerHub (arm64)
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.arm64
          platform: linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}